[package]
name = "AdvancedComputerGraphic-rs"
version = "0.1.0"
authors = ["jack111331 <jack111331@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.18.0"
libm = "0.2.1"